version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 945157288197.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - docker build -t office -f ./apps/office/Dockerfile .
      - docker tag office:latest 945157288197.dkr.ecr.eu-north-1.amazonaws.com/office:latest

  post_build:
    commands:
      - docker push 945157288197.dkr.ecr.eu-north-1.amazonaws.com/office:latest